site_name: Spoofax
site_author: Spoofax Team
site_description: Spoofax language workbench

copyright: "Copyright &copy; 2010-2021 Spoofax Team"

repo_name: spoofax
repo_url: https://github.com/metaborg/spoofax
edit_uri: https://github.com/metaborg/spoofax-docs/edit/main/docs

nav:
  - Home:
    - index.md
    - Releases: releases.md
    - About: about.md
    - Support: support.md
  - Tutorials:
    - tutorials/index.md
  - How-Tos:
    - howtos/index.md
    - howtos/install-eclipse-bundle.md
    - howtos/install-eclipse-plugin-manually.md
    - howtos/install-cli.md
  - Reference:
    - reference/index.md
  - Background:
    - background/index.md

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/sticky-note
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: spoofax
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

extra_css:
  - assets/styles.css
    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - macros

extra:
  os:
    windows: ":fontawesome-brands-windows: Windows"
    linux: ":fontawesome-brands-linux: Linux"
    macos: ":fontawesome-brands-apple: macOS"
