site_name: Spoofax
site_author: Spoofax Team
site_description: Spoofax language workbench
site_url: https://www.spoofax.dev/spoofax-docs/

copyright: "Copyright &copy; 2010-2021 Spoofax Team"

repo_name: spoofax
repo_url: https://github.com/metaborg/spoofax
edit_uri: https://github.com/metaborg/spoofax-docs/edit/main/docs

nav:
  - Home:
    - index.md
    - getting-started.md
    - nightly.md
  - Tutorials:
    - tutorials/index.md
  - How-Tos:
    - howtos/index.md
    - howtos/install-eclipse-bundle.md
    - howtos/install-eclipse-plugin-manually.md
    - howtos/install-from-source.md
    - Editor Services:
      - howtos/editor-services/rename-refactoring.md
  - References:
    - references/index.md
    - Configuation:
      - references/config/index.md
    - Syntax:
      - references/syntax/index.md
      - references/syntax/structure.md
      - references/syntax/concepts.md
      - references/syntax/constructs.md
      - references/syntax/normalization.md
      - references/syntax/disambiguation.md
      - references/syntax/layout-sensitive.md
      - references/syntax/recovery.md
      - references/syntax/configuration.md
    - Static Semantics:
      - references/statix/index.md
      - references/statix/modules.md
      - references/statix/signatures.md
      - references/statix/terms.md
      - references/statix/constraints.md
      - references/statix/rules.md
      - references/statix/types.md
      - references/statix/tests.md
      - references/statix/stratego-api.md
    - Data Flow Analysis:
      - references/flowspec/introduction.md
      - references/flowspec/structure.md
      - references/flowspec/Stratego_API.md
      - references/flowspec/testing.md
      - references/flowspec/glossary.md
      - references/flowspec/references.md
    - Transformation:
      - references/stratego/index.md
      - references/stratego/lexical.md
      - references/stratego/modules.md
      - references/stratego/terms.md
      - references/stratego/types.md
      - references/stratego/rewrite-rules.md
      - references/stratego/strategies.md
      - references/stratego/strategy-combinators.md
      - references/stratego/dynamic-rules.md
      - references/stratego/concrete-syntax.md
      - references/stratego/overlays.md
    - Testing:
      - references/testing/index.md
    - Editor Services:
      - references/editor-services/index.md
      - references/editor-services/esv.md
      - references/editor-services/analysis.md
      - references/editor-services/file-extensions.md
      - references/editor-services/hover.md
      - references/editor-services/menus.md
      - references/editor-services/on-save.md
      - references/editor-services/outline.md
      - references/editor-services/parsing.md
      - references/editor-services/reference-resolution.md
      - references/editor-services/renaming.md
      - references/editor-services/stratego.md
      - references/editor-services/syntax-highlighting.md
    - Pipelines:
      - references/pipelines/index.md
      - references/pipelines/modules.md
      - references/pipelines/types.md
      - references/pipelines/generics.md
      - references/pipelines/functions.md
      - references/pipelines/expressions.md
  - Background:
    - background/index.md
    - background/documentation.md
    - Bibliography:
      - background/bibliography/stratego.md

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/sticky-note
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: spoofax
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

extra_css:
  - assets/styles.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - macros:
      module_name: docs/macro
  - bibtex:
      bib_dir: "bibliographies"
      cite_style: "pandoc"
