site_name: Spoofax
site_author: Spoofax Team
site_description: Spoofax language workbench
site_url: https://www.spoofax.dev/spoofax-docs/

copyright: "Copyright &copy; 2010-2021 Spoofax Team"

repo_name: spoofax
repo_url: https://github.com/metaborg/spoofax
edit_uri: https://github.com/metaborg/spoofax-docs/edit/main/docs

nav:
  - Home:
    - index.md
    - getting-started.md
    - nightly.md
  - Tutorials:
    - tutorials/index.md
  - How-Tos:
    - howtos/index.md
    - howtos/install-eclipse-bundle.md
    - howtos/install-eclipse-plugin-manually.md
    - howtos/install-from-source.md
  - References:
    - references/index.md
    - Syntax:
      - references/syntax/sdf3.md
      - references/syntax/structure.md
      - references/syntax/concepts.md
      - references/syntax/constructs.md
      - references/syntax/normalization.md
      - references/syntax/disambiguation.md
      - references/syntax/layout-sensitive.md
      - references/syntax/recovery.md
      - references/syntax/configuration.md
    - Transformation:
      - references/stratego/index.md
      - references/stratego/modules.md
      - references/stratego/terms.md
      - references/stratego/types.md
      - references/stratego/rewrite-rules.md
      - references/stratego/strategies.md
      - references/stratego/strategy-combinators.md
      - references/stratego/dynamic-rules.md
      - references/stratego/concrete-syntax.md
    - Static Semantics:
      - references/statix/index.md
      - references/statix/modules.md
      - references/statix/signatures.md
      - references/statix/terms.md
      - references/statix/constraints.md
      - references/statix/rules.md
      - references/statix/types.md
      - references/statix/tests.md
      - references/statix/stratego-api.md
  - Background:
    - background/index.md
    - background/documentation.md
    - Bibliography:
      - background/bibliography/stratego.md

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/sticky-note
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: spoofax
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

extra_css:
  - assets/styles.css
  - assets/fonts.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date:
      enabled_if_env: CI
  - macros
  - bibtex:
      bib_dir: "bibliographies"
      cite_style: "pandoc"

extra:
  os:
    windows: ":fontawesome-brands-windows: Windows"
    linux: ":fontawesome-brands-linux: Linux"
    macos: ":fontawesome-brands-apple: macOS"
  releases:
    stable:
      eclipse:
        bundle_jre:
          macos:
            intel: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.15/org.metaborg.spoofax.eclipse.dist-2.5.15-macosx-x64-jre.tar.gz"
          linux:
            x64: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.15/org.metaborg.spoofax.eclipse.dist-2.5.15-linux-x64-jre.tar.gz"
          windows:
            x64: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.15/org.metaborg.spoofax.eclipse.dist-2.5.15-windows-x64-jre.zip"
            x86: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.15/org.metaborg.spoofax.eclipse.dist-2.5.15-windows-x86-jre.zip"
        bundle_nojre:
          macos:
            intel: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.16/org.metaborg.spoofax.eclipse.dist-2.5.16-macosx-x64.tar.gz"
          linux:
            x64: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.16/org.metaborg.spoofax.eclipse.dist-2.5.16-linux-x64.tar.gz"
          windows:
            x64: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.16/org.metaborg.spoofax.eclipse.dist-2.5.16-windows-x64.zip"
            x86: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/2.5.16/org.metaborg.spoofax.eclipse.dist-2.5.16-windows-x86.zip"
        plugin: "http://artifacts.metaborg.org/content/unzip/releases-unzipped/org/metaborg/org.metaborg.spoofax.eclipse.updatesite/2.5.15/org.metaborg.spoofax.eclipse.updatesite-2.5.15-assembly.zip-unzip/"
    nightly:
      eclipse:
        bundle_jre:
          macos:
            intel: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-macosx-x64-jre.tar.gz"
          linux:
            x64: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-linux-x64-jre.tar.gz"
          windows:
            x64: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-windows-x64-jre.zip"
            x86: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-windows-x86-jre.zip"
        bundle_nojre:
          macos:
            intel: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-macosx-x64.tar.gz"
          linux:
            x64: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-linux-x64.tar.gz"
          windows:
            x64: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-windows-x64.zip"
            x86: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/spoofax-windows-x86.zip"
        plugin: "http://buildfarm.metaborg.org/job/metaborg/job/spoofax-releng/job/master/lastSuccessfulBuild/artifact/dist/spoofax/eclipse/site/"



    base_url: "http://artifacts.metaborg.org/service/local/repositories/releases/content/org/metaborg/org.metaborg.spoofax.eclipse.dist/"
    version: "2.5.15"
    base_file: "/org.metaborg.spoofax.eclipse.dist-"
    macos-file: "-macosx-x64-jre.tar.gz"
    macos: "{{ releases.base_url }}{{ releases.version }}{{ releases.base_file }}{{ releases.version }}{{ releases.macos-file }}"
